// Generated by `sflock bind` from *.scripts.ts. Do not edit — re-bind.

export interface Card {
  name?: string | null;
  /**
   * Full About prose with line breaks preserved; null if the profile has no About section.
   */
  about?: string | null;
  headline?: string | null;
  location?: string | null;
  profileUrl: string;
}

export interface Experience {
  positions: {
    title: string | null;
    company: string | null;
    duration: string | null;
    location: string | null;
    dateRange: string | null;
    /**
     * LinkedIn /company/ or /school/ page; null when the org has no LinkedIn page
     */
    companyUrl: string | null;
    description: string | null;
    employmentType: string | null;
  }[];
}

export interface Education {
  education: {
    degree: string | null;
    school: string | null;
    /**
     * null when the profile lists no dates for the entry
     */
    dateRange: string | null;
    /**
     * LinkedIn /school/ or /company/ page; null when the school has no LinkedIn page
     */
    schoolUrl: string | null;
    /**
     * only parseable when a date line precedes it; null otherwise
     */
    description: string | null;
  }[];
}
