// Generated by `sflock pull --client notion --model 8ae4d7b7-884c-82ec-8c2e-875acbcd57bb`. Do not edit — re-pull.

export interface Leads {
  "AI draft"?: string;
  "AI note"?: string;
  /**
   * relation → dad4d7b7-884c-83e7-8c03-076d365669b4
   */
  Campaign?: string[];
  /**
   * relation → b9b4d7b7-884c-8368-80d9-070bdf14ef0f
   */
  Company?: string[];
  Draft?: string;
  "Draft Notes"?: string;
  Grading?: string;
  "Human note"?: string;
  /**
   * relation → 9c04d7b7-884c-820b-b2a2-874c61f00074
   */
  Job?: string[];
  /**
   * ISO 8601 date or date-time
   */
  "Last Interacted"?: string;
  Name: string;
  /**
   * ISO 8601 date or date-time
   */
  "Next Action Due"?: string;
  /**
   * relation → 92e4d7b7-884c-83c9-b85e-07663f5439f2
   */
  Person?: string[];
  /**
   * Notion user ids
   */
  "Person 1"?: string[];
  Status?:
    | "one member reviewed"
    | "Not Started"
    | "Team reviewed"
    | "Bad draft"
    | "Daniel reviewed"
    | "Sent"
    | "Accepted"
    | "Replied"
    | "Booked"
    | "Rejected"
    | "Not Qualified";
  Tier?: "golden" | "T1" | "T2" | "T3" | "No job offer" | "not a relevant job offer";
}
