// Generated by `sflock pull --client notion --model 8de4d7b7884c839fbb048185e1eb9d30`. Do not edit — re-pull.

export interface People {
  About?: string;
  Connections?: number;
  /**
   * relation → b9b4d7b7-884c-8368-80d9-070bdf14ef0f
   */
  "Current Company"?: string[];
  Experiences?: string;
  Followers?: number;
  Headline?: string;
  /**
   * relation → 8ae4d7b7-884c-82ec-8c2e-875acbcd57bb
   */
  Leads?: string[];
  "LinkedIn URL"?: string;
  Location?: string;
  Name: string;
  Posts?: string;
}
