#!/usr/bin/env node
// sflock — the setup CLI. Populates an agent's schema with destination Ground Truth.
//   sflock pull --agent <id> --client <name> --model <m> [--model <m> …]
// writes agents/<id>/schema/<model>.ts — the model's writable contract, as a TS type.
//
// Each client describes a model as a JSON Schema (notion); sflock is the generic layer
// that compiles that schema straight to a TS type — no intermediate .json on disk.
// It holds no per-client semantics: describe → compile → write.

import "./env.js";
import { Command } from "commander";
import { mkdir, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { compile } from "json-schema-to-typescript";
import { bind } from "./scripts.js";
import * as hubspot from "./clients/hubspot.js";
import * as notion from "./clients/notion.js";

// Client registry: name → the client that can describe a model. Only clients with a
// property surface belong here (reduck is a runner, not a schema source). Add one = add an entry.
const CLIENTS = { hubspot, notion } as const;
type ClientName = keyof typeof CLIENTS;

const collect = (v: string, acc: string[]): string[] => [...acc, v];

// The TS type / file name: the schema's own title when the client gives one (notion's
// JSON Schema), else the model token. Stripped to a safe identifier so it's both a valid
// filename and a valid TS interface name.
const typeName = (model: string, described: unknown): string => {
	const title =
		described && typeof described === "object" && !Array.isArray(described)
			? (described as { title?: unknown }).title
			: undefined;
	return (typeof title === "string" ? title : model).replace(/[^\w.-]+/g, "_");
};

// Number of writable properties in a described model — a JSON Schema's `properties`, or
// a flat property array (hubspot, pending alignment) — for the progress line.
const propCount = (described: unknown): number =>
	Array.isArray(described)
		? described.length
		: Object.keys((described as { properties?: object }).properties ?? {}).length;

const program = new Command()
	.name("sflock")
	.description("Setup CLI — populate an agent's schema with destination Ground Truth.");

program
	.command("pull")
	.description("Compile each model's writable contract → agents/<agent>/schema/<model>.ts (TS type)")
	.requiredOption("--agent <id>", "agent under agents/ to populate")
	.requiredOption("--client <name>", `destination client (${Object.keys(CLIENTS).join(", ")})`)
	.requiredOption("--model <name>", "object type to pull (repeatable)", collect, [])
	.action(async ({ agent, client, model }: { agent: string; client: string; model: string[] }) => {
		const c = CLIENTS[client as ClientName];
		if (!c) program.error(`unknown client "${client}" — one of: ${Object.keys(CLIENTS).join(", ")}`);
		const agentDir = join("agents", agent);
		const ok = await stat(agentDir).then((s) => s.isDirectory()).catch(() => false);
		if (!ok) program.error(`no agent "${agent}" — ${agentDir}/ does not exist.`);
		const dir = join(agentDir, "schema");
		await mkdir(dir, { recursive: true });
		for (const m of model) {
			const described = await c.describe(m);
			const name = typeName(m, described);
			const ts = await compile(described as object, name, {
				bannerComment: `// Generated by \`sflock pull --client ${client} --model ${m}\`. Do not edit — re-pull.`,
				additionalProperties: false
			});
			const path = join(dir, `${name}.ts`);
			await writeFile(path, ts);
			console.error(`${m}: ${propCount(described)} writable properties → ${path}`);
		}
	});

program
	.command("bind")
	.description("Compile a reduck-derived client's script manifest → src/clients/<client>.schema.ts (TS output types)")
	.requiredOption("--client <name>", "client under src/clients/ with a <name>.scripts.ts manifest")
	.action(async ({ client }: { client: string }) => {
		const { scripts } = (await import(`./clients/${client}.scripts.js`)) as { scripts: Record<string, string> };
		const path = join("src", "clients", `${client}.schema.ts`);
		await writeFile(path, await bind(scripts));
		console.error(`${client}: ${Object.keys(scripts).length} scripts → ${path}`);
	});

program.parseAsync().catch((e: Error) => {
	console.error(`error: ${e.message}`);
	process.exit(1);
});
