// Manifest → TS. For each script in a client's manifest, fetch its contract (ground
// truth) and compile its output schema into an interface; emit one barrel of interfaces.
// The source-side twin of sflock pull: read → compile → write, no per-client semantics.

import { compile } from "json-schema-to-typescript";
import { read } from "./clients/reduck.js";

const pascal = (s: string): string => s.replace(/(^|_)(\w)/g, (_, __, c: string) => c.toUpperCase());

export const bind = async (scripts: Record<string, string>): Promise<string> => {
	const parts = await Promise.all(
		Object.entries(scripts).map(async ([name, addr]) => {
			const { output } = await read(addr);
			return compile(output as object, pascal(name), { bannerComment: "", additionalProperties: false });
		})
	);
	return `// Generated by \`sflock bind\` from *.scripts.ts. Do not edit — re-bind.\n\n${parts.join("\n")}`;
};
